In [41]:
import numpy as np
np.sqrt(25) #raiz cuadrada

5.0

#### 1 Arrays


In [42]:
a=[1,2,3,4,5]
type (a)

list

In [43]:
np.array(a)

array([1, 2, 3, 4, 5])

In [44]:
b=np.arange(4,25,5)
print(b)

[ 4  9 14 19 24]


In [45]:
c=np.linspace(1,40,20)
print(c)


[ 1.          3.05263158  5.10526316  7.15789474  9.21052632 11.26315789
 13.31578947 15.36842105 17.42105263 19.47368421 21.52631579 23.57894737
 25.63157895 27.68421053 29.73684211 31.78947368 33.84210526 35.89473684
 37.94736842 40.        ]


In [46]:
d=np.zeros(10)
e=np.ones(10)

print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Dimensiones

In [47]:
aray_2d=np.array([d,e])
print(aray_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [48]:
aray_2d.shape

(2, 10)

In [49]:
aray_2d.size

20

In [50]:
aray_2d.ndim

2

#### Operaciones con aarays

In [51]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]

In [52]:
array_1=np.array(l1)
array_2=np.array(l2)

In [53]:
array_1*array_2



array([ 6, 14, 24, 36, 50])

In [54]:
[num1*num2 for num1, num2 in zip(l1,l2)]

[6, 14, 24, 36, 50]

#### Funciones

In [55]:
aray_2d.shape

(2, 10)

In [56]:
f=np.reshape(aray_2d,(4,5))
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
A=np.array([[1,2,3,4,5],[10,20,30,40,52]])
      #DIMENSIONES VERTICALES A HORIZONTALES

In [58]:
A.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 52]])

In [59]:
z=np.random.randint(0,300)


In [60]:
aray_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
np.where(aray_2d == 1, aray_2d*10, aray_2d-5)

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

#### estadistica

##### DISTRIBUCIONES

In [66]:
ARRAY_NORMAL= np.random.normal(1.75,.05,100) 

In [67]:
ARRAY_NORMAL

array([1.73047829, 1.71255657, 1.76840736, 1.74653068, 1.61858737,
       1.73380023, 1.77202952, 1.77526415, 1.66811242, 1.84487317,
       1.75177678, 1.88605778, 1.80250728, 1.75272764, 1.75892031,
       1.75157033, 1.74011223, 1.72026464, 1.69082032, 1.7319234 ,
       1.68884638, 1.84818818, 1.80529538, 1.77509771, 1.82737494,
       1.69450121, 1.75689882, 1.79007044, 1.7020543 , 1.74143117,
       1.67101209, 1.71260045, 1.67725113, 1.69126641, 1.69225079,
       1.62723383, 1.7519985 , 1.77605331, 1.7641537 , 1.72587109,
       1.8343844 , 1.72372471, 1.65224305, 1.70409429, 1.7250319 ,
       1.74753607, 1.79163979, 1.73791738, 1.80760789, 1.65641141,
       1.71879087, 1.72123182, 1.77895695, 1.6692721 , 1.82188932,
       1.73190709, 1.74259768, 1.75284394, 1.83445761, 1.6937293 ,
       1.75119592, 1.83360222, 1.72877087, 1.7216168 , 1.70427288,
       1.75066202, 1.69018705, 1.80276987, 1.78563843, 1.73767471,
       1.70194134, 1.75284831, 1.72022023, 1.71811841, 1.78979

In [68]:
np.mean(ARRAY_NORMAL)

1.7490786020250422

In [69]:
np.median(ARRAY_NORMAL)

1.7445641836362034

In [ ]:
np.std(ARRAY_NORMAL) #desviacion estandfar